/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import drivercardhostapp.DriverCardHostApp;
import drivercardhostapp.commons.constants.APPLET_CONSTANTS;
import drivercardhostapp.commons.constants.AUTH_CONSTANTS;
import drivercardhostapp.commons.constants.ISO7816;
import drivercardhostapp.commons.utils.ConvertData;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.smartcardio.CardException;
import javax.smartcardio.ResponseAPDU;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class EnterPinGUI extends javax.swing.JFrame {
    private MainGUI mainGUI;
    private final DriverCardHostApp host;
    /**
     * Creates new form EnterPinGUI
     */
    public EnterPinGUI(DriverCardHostApp host) {
        initComponents();
        this.host = host;
        mainGUI = new MainGUI(host);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEnter = new javax.swing.JButton();
        tfPassword = new javax.swing.JPasswordField();
        txtStatus = new javax.swing.JLabel();
        btnUnlock = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NHẬP MÃ PIN GỒM 4 CHỮ SỐ NHÉ !");

        btnEnter.setText("OK");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        btnUnlock.setText("MỞ KHÓA");
        btnUnlock.setEnabled(false);
        btnUnlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnlockActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(txtStatus))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)
                                .addGap(66, 66, 66)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUnlock)
                            .addComponent(btnEnter))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtStatus)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnter)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnlock)
                    .addComponent(jButton1))
                .addGap(101, 101, 101))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        char[] pinText = tfPassword.getPassword(); // lay ma pin
        
        try {
            ResponseAPDU response = host.sendAPDU(
                    APPLET_CONSTANTS.CLA, APPLET_CONSTANTS.VERIFY, AUTH_CONSTANTS.AUTH,
                    (byte)2, ConvertData.charArrayToByteArray(pinText));
            String check = Integer.toHexString(response.getSW());
            System.out.println(check);
            
            switch(check){
                case ISO7816.SW_NO_ERROR:
                    // verify success
                    pushToMainWindow();
                    break;
                case AUTH_CONSTANTS.SW_WRONG_PIN_LEN:
                    txtStatus.setText("Độ dài là 6 ký tự !");
                    break;
                case AUTH_CONSTANTS.SW_OVER_TRY_TIMES:
                    txtStatus.setText("Qúa số lần thử. Tài khoản đã bị khóa !");
                    btnUnlock.setEnabled(true);
                    break;
                case AUTH_CONSTANTS.SW_VERIFICATION_FAILED:
                    txtStatus.setText("Sai mã PIN");
                    break;
            }
        } catch (CardException ex) {
            Logger.getLogger(EnterPinGUI.class.getName()).log(Level.SEVERE, null, ex);
            showFailureDialog();
        }
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnUnlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnlockActionPerformed
        try {
            ResponseAPDU response = host.sendAPDU(
                    APPLET_CONSTANTS.CLA, APPLET_CONSTANTS.UNBLOCK, AUTH_CONSTANTS.AUTH,
                    (byte)2, null);
             String check = Integer.toHexString(response.getSW());
             if(check.equals(ISO7816.SW_NO_ERROR)){
                 btnUnlock.setEnabled(false);
                 txtStatus.setText("Đã mở khóa. Vui lòng nhập lại mã PIN");
             }else{
                 showFailureDialog();
             }
        }catch (CardException ex) {
            Logger.getLogger(EnterPinGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi");
        }
    }//GEN-LAST:event_btnUnlockActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            ResponseAPDU response = host.sendAPDU(
                    APPLET_CONSTANTS.CLA, APPLET_CONSTANTS.READ, AUTH_CONSTANTS.AUTH,
                    (byte)2, null);
             String check = Integer.toHexString(response.getSW());
             if(check.equals(ISO7816.SW_NO_ERROR)){
                 System.out.println(Arrays.toString(response.getData()));
             }else{
                 showFailureDialog();
             }
        }catch (CardException ex) {
            Logger.getLogger(EnterPinGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pushToMainWindow(){
        this.setVisible(false);
        mainGUI.setLocationRelativeTo(null);
        mainGUI.setVisible(true);      
    }
    
    private void showFailureDialog(){
        JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi");
    }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EnterPinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EnterPinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EnterPinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EnterPinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EnterPinGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnUnlock;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JLabel txtStatus;
    // End of variables declaration//GEN-END:variables
}
